name: Denopendabot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: hasundue/denopendabot@0.6.2
        with:
          user-token: ${{ secrets.GH_TOKEN }}
